import Head from 'next/head'
import Layout from '../components/layout'
import Header from '../components/header'
import Sidebar from '../components/sidebar'
import Main from '../components/main'
import Footer from '../components/footer'
import { useEffect } from 'react'
import getStreams from '../functions/get-streams'


export default function Home() {
  useEffect(() => {
    getStreams('helix').then(res => console.log(res))
  }, [])

  return (
    <Layout>
      <Head>
        <title>The Best Streaming</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <Sidebar />
      <Main />
      <Footer />





      
    </Layout>
  )
}
